#!/usr/bin/env bash

set -e
trap "kill 0" EXIT

make -Cout -j4

from=$1
to=$2
[ $from ] || from=101
[ $to ] || to=140

P1=Local
P2=Empty
TEAM_SIZE=1 
LEVEL=Complex
LEN=300
ARGS="--check-simulation --batch"
LR_ARGS=--batch-mode
BASE_PORT=31110

sum=0
for i in $(seq $from $to); do
    SEED=$i
    res=$(source scripts/run-game.sh)
    echo "$i $res"
    sum=$((sum + res))
done
echo "Total errors: $sum"

wait
